[versions]
agp = "8.9.0"
kotlin = "2.1.10"
core-ktx = "1.15.0"
appcompat = "1.7.0"
material = "1.13.0-alpha11"
constraintlayout = "2.2.1"
hilt = "2.55"
fragmentKtx = "1.8.6"
xxPermission = "20.0"
glide = "4.16.0"
activity = "1.10.1"
mlkit = "16.0.1"
photoView = "2.3.0"
opencv = "4.11.0"
libsu = "6.0.0"
smali = "2.5.2"
okhttp = "4.12.0"
retrofit = "2.11.0"
andServer = "2.1.12"
umengCommon = "9.8.8"
umengAsms = "1.8.7.2"
umengApm = "2.0.6"
junit = "4.13.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
xxPermission = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxPermission" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
mlkitTextRecognitionChinese = { group = "com.google.mlkit", name = "text-recognition-chinese", version.ref = "mlkit" }
photoView = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoView" }
opencv = { group = "org.opencv", name = "opencv", version.ref = "opencv" }
libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
libsu-service = { group = "com.github.topjohnwu.libsu", name = "service", version.ref = "libsu" }
libsu-nio = { group = "com.github.topjohnwu.libsu", name = "nio", version.ref = "libsu" }
baksmali = { group = "org.smali", name = "baksmali", version.ref = "smali" }
dexlib2 = { group = "org.smali", name = "dexlib2", version.ref = "smali" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
andserver-api = { group = "com.yanzhenjie.andserver", name = "api", version.ref = "andServer" }
andserver-processor = { group = "com.yanzhenjie.andserver", name = "processor", version.ref = "andServer" }
andserver-plugin = {group = "com.yanzhenjie.andserver", name = "plugin", version.ref = "andServer"}
umeng-common = { group = "com.umeng.umsdk", name = "common", version.ref = "umengCommon" }
umeng-asms = { group = "com.umeng.umsdk", name = "asms", version.ref = "umengAsms" }
umeng-apm = { group = "com.umeng.umsdk", name = "apm", version.ref = "umengApm" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }